- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "HELLO {{course | default ('Ansible') }}"

- name: upper case
  host: localhost
  vars:
    greeting: "Hello Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"